# This is a basic workflow to help you get started with Actions

name: "CI â–¶ Build check (Stub)"

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    #types: [opened, synchronize, closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: []

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci_job_cancel_test_win:
    name: CI job cancel test (OS Windows)
    runs-on: windows-latest
    steps:
      - name: Job cancel
        shell: cmd
        run: |
          ECHO Hello world!
          ECHO ----------------------------------------
          EXIT 0

  ci_job_cancel_test_lin:
    name: CI job cancel test (OS *nux)
    runs-on: ubuntu-latest
    steps:
      - name: Job cancel
        shell: bash
        run: |
          echo "Hello world!"
          echo "----------------------------------------"
          exit 0

  ci_job_cancel_test_mac:
    name: CI job cancel test (macOS)
    runs-on: macos-latest
    steps:
      - name: Job cancel
        shell: sh
        run: |
          echo "Hello world!"
          echo "----------------------------------------"
          exit 0
